### ISSUE TITLE
Reproduce problem,my mean score on unknown task is like 8% or 7%,where did i do wrong ?Any advices about improving my score?

### ISSUE THREAD

**Issue by pussinmood** [PierreMarza/task_conditioned_adaptation#4]
On known task,so far so good
![Pasted Graphic](https://github.com/user-attachments/assets/38fe65a6-ad6d-4053-8974-942201c98a1b)
But comes to unknown ......  a disaster
<img width="1068" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/6543825a-fdf6-44e6-bf5b-ff23b0f02457">
Hope you help me out ~

**Comment by PierreMarza** [comment]
Hi, first of all, it is expected to reach lower performance on unknown tasks compared with known ones as the problem to solve is much harder: adapting to a new task unseen at training time (unlike known tasks) from only 5 demonstrations. If you look at Fig. 6 in our paper (https://arxiv.org/pdf/2402.07739) you will see that we reach low performance in some of the tasks.

However, you might be able to reach higher performance on this specific _faucet-close_ task. I would need more information about what you have been doing because there are 2 steps here: (1) task embedding search, and (2) eval using the learned task embeddings. Have you modified the code or some of the hyperparameters? What commands have you launched?

**Comment by pussinmood** [comment]
I did a 50 epoch train like you taught in the readme using cloudserver ,and i downloaded the ckpt_49.pth to my laptop,then i did 2 steps all in my laptop to eval ,maybe the cloudserver's hyperparameters are different to my laptop ,i will try do things on cloud .Sorry about my various low level mistakes

**Comment by PierreMarza** [comment]
I would suggest trying the following:

1) First, run these 2 steps (TE search + eval) for all 15 unknown tasks using **the pre-trained model we provide** (not the one you trained yourself) and report the average score across all unknown tasks.

2) Then, do the same with your model (TE search + eval on all 15 unknown tasks and report average score). But instead of taking the last checkpoint for your model (ckpt_49.pth), I would suggest doing first **a validation on the known tasks**: for all checkpoints (or at least as much as you can depending on the compute resources you have...), run the evaluation with **val_known** as the  _eval_type_ (_--eval_type val_known_) for all known tasks and pick the checkpoint that has the highest average validation score across all known tasks as the one you will use to do TE search + eval on all unknown tasks.

Please let me know if you need more information!

**Comment by pussinmood** [comment]
really grateful for your advices~.~wish you have a good day
